const Options = [
  "Reportar Zonas de Risco",
  " Hospitais mais Próximos",
  "Zonas mais Afectadas",
  "Sair",
];

const ScaleProps = {
  option_one: [
    "seeProvinces",
    "insertProvince",
    "seeMunicipes",
    "insertMunicipes",
    "sendReport",
  ],
  option_two: [
    "seeProvinces",
    "insertProvince",
    "seeMunicipes",
    "insertMunicipes",
    "showHospitals",
  ],
  option_three: ["showAffectedAreas"],
};

const Provinces = [
  "Benguela",
  "Bié",
  "Cabinda",
  "Cuando Cubango",
  "Cunene",
  "Huambo",
  "Huíla",
  "Luanda",
  "Lunda Norte",
  "Lunda Sul",
  "Malanje",
  "Moxico",
  "Namibe",
  "Uíge",
  "Zaire",
];

const Municipes = [
  [
    "Balombo",
    "Baía Farta",
    "Benguela",
    "Bocoio",
    "Caimbambo",
    "Catumbela",
    "Chongorói",
    "Cubal",
    "Ganda",
    "Lobito",
  ],
  [
    "Andulo",
    "Camacupa",
    "Catabola",
    "Chinguar",
    "Chitembo",
    "Cuemba",
    "Cunhinga",
    "Cuíto",
    "Nharea",
  ],
  ["Belize", "Buco-Zau", "Cabinda", "Cacongo"],
  [
    "Calai",
    "Cuangar",
    "Cuchi",
    "Cuito Cuanavale",
    "Dirico",
    "Mavinga",
    "Menongue",
    "Nancova",
    "Rivungo",
  ],
  ["Cahama", "Cuanhama", "Curoca", "Cuvelai", "Namacunde", "Ombadja"],
  [
    "Bailundo",
    "Cachiungo",
    "Caála",
    "Ecunha",
    "Huambo",
    "Londuimbali",
    "Longonjo",
    "Mungo",
    "Chicala-Choloanga",
    "Chinjenje",
    "Ucuma",
  ],
  [
    "Caconda",
    "Cacula",
    "Caluquembe",
    "Chiange",
    "Chibia",
    "Chicomba",
    "Chipindo",
    "Cuvango",
    "Humpata",
    "Jamba",
    "Lubango",
    "Matala",
    "Quilengues",
    "Quipungo",
  ],
  [
    "Belas",
    "Cacuaco",
    "Cazenga",
    "Ícolo e Bengo",
    "Luanda",
    "Quilamba Quiaxi",
    "Quissama",
    "Talatona",
    "Viana",
  ],
  [
    "Cambulo",
    "Capenda-Camulemba",
    "Caungula",
    "Chitato",
    "Cuango",
    "Cuílo",
    "Lóvua",
    "Lubalo",
    "Lucapa",
    "Xá-Muteba",
  ],
  ["Cacolo", "Dala", "Muconda", "Saurimo"],
  [
    "Cacuso",
    "Calandula",
    "Cambundi-Catembo",
    "Cangandala",
    "Caombo",
    "Cuaba Nzoji",
    "Cunda-Dia-Baze",
    "Luquembo",
    "Malanje",
    "Marimba",
    "Massango",
    "Mucari",
    "Quela",
    "Quirima",
  ],
  [
    "Alto Zambeze",
    "Bundas",
    "Camanongue",
    "Léua",
    "Luau",
    "Luacano",
    "Luchazes",
    "Cameia",
    "Moxico",
  ],
  ["Bibala", "Camucuio", "Moçâmedes", "Tômbua", "Virei"],
  [
    "Alto Cauale",
    "Ambuíla",
    "Bembe",
    "Buengas",
    "Bungo",
    "Damba",
    "Milunga",
    "Mucaba",
    "Negage",
    "Puri",
    "Quimbele",
    "Quitexe",
    "Sanza Pombo",
    "Songo",
    "Uíge",
    "Zombo",
  ],
  ["Cuimba", "Mabanza Congo", "Nóqui", "Nezeto", "Soio", "Tomboco"],
];

export { Options, Provinces, Municipes };
